name: Build and Test

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Setup Node.js and cache Yarn dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json' # キャッシュキーをより正確に

      - name: Boot iOS Simulator
        run: open -a Simulator

      - name: Install root dependencies
        run: npm install --package-lock-only

      - name: Install frontend dependencies
        run: npm install --package-lock-only --legacy-peer-deps
        working-directory: ./frontend

      - name: Run Lint
        run: npm run lint
      - name: Run Tests
        run: npm test
        working-directory: ./frontend

      - name: Run E2E Tests
        run: 
          npm run detox -- --configuration ios.sim.debug --cleanup
          npm run detox test -- --configuration ios.sim.debug
        working-directory: ./frontend
        env:
          DETOX_E2E: 'true'
          CI: 'true'
