name: Build and Test

on: [push]

jobs:
  test:
    runs-on: macos-latest
    env:
      NPM_CONFIG_LEGACY_PEER_DEPS: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.4'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Boot iOS Simulator
        run: open -a Simulator

      - name: Install root dependencies
        run: npm ci

      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Prebuild native projects (Expo)
        run: npm run prebuild
        working-directory: ./frontend
        env:
          DETOX_E2E: 'true'

      - name: Run Lint on rootproject
        run: npm run lint

      - name: Run Lint on frontend
        run: npm run lint
        working-directory: ./frontend

      - name: Run Unit Tests
        run: npm test
        working-directory: ./frontend

      - name: Build E2E (Detox)
        run: npm run test:e2e:ios:build
        working-directory: ./frontend

      - name: Run E2E Tests (Detox with Metro and .e2e resolution)
        run: npm run test:e2e:ios:ci:with-metro
        working-directory: ./frontend
        env:
          DETOX_E2E: 'true'
          CI: 'true'
