name: Build and Test

on: [push]

jobs:
  test:
    runs-on: macos-14-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js and cache Yarn dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock' # キャッシュキーをより正確に

      - name: Remove package-lock.json to avoid conflicts
        run: rm -f package-lock.json frontend/package-lock.json

      - name: Install root dependencies
        run: yarn install --frozen-lockfile

      - name: Install frontend dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./frontend

      - name: Run Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test
        working-directory: ./frontend

      - name: Run E2E Tests
        run: 
          yarn detox --configuration ios.sim.debug --cleanup
          yarn detox test --configuration ios.sim.debug
        working-directory: ./frontend
        env:
          DETOX_E2E: 'true'
          CI: 'true'
